dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script: pytest

notifications:
  slack:
    rooms:
      secure: X4ZnpazliTKw7BqXqY3QGl+OPtF1A/WE/mboyOEan8Drm/OuRzljhqd+t1d8/7auvO3eoB1WFuSJPnA7FfSwiaGxxavJBeh2SPausjEZvsZ1PlpR7dpz1KnoCxK48Qm6GD3ChLWe4M7ltf6Fshs3lkLngVmNtSrZBXWH5Ztl9uRN+wTORBWe3BIRU3Dt99XTz15rso3dLQLLLzwEDN/Wwv2Z8thUed6fVJcVi39HiFxS98yJ1aX/miGaVGLra7x9MeuHHIKNKNnkI/pi5xTNaFpjboRrdIsjeRuFRBeKnkPPx8lEZo1iq9nPiwnDd3QIt3ELCiAm9/NLEy46Ayyur5ofV+TZ1F1lycm41BEXGCo8xoQjrVK3g9zh4i0ACwkya8JEd5gFRY2xkXmCfg3NVWVHguzDXd2c13bCdfNCxJzi5/b+GV+zV+BI9iF2IrrN04Zh8uIrOYDkKDuL8MPwYsbWlkOoEbtd7Og3ObkxaRy72eYuH2orJfKWdLvZRcvMeFpF2QsM9you/suLYo06GbOHCtVcwzHLuYkvbKJLkU2RS3GW5avXY3mZwNJ7wqxWop0KNpJo8em3LLm8dkztvikC5UvxJVi0Vq/j7rtj/lXMugyOTQLmS1NJSY+SgBwS/QVMacryZbDN/MMplu87AHeRveUX9TZ6pPfyHII6ziI=
