version: 2

jobs:
  test:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest

workflows:
  version: 2
  test:
    jobs:
      - test